### PR TITLE
Ft fixes

### PR DESCRIPTION
**Pull request by bolorundurovj**

### CODE REVIEW

**Comment by bolorundurovj** [comment]
@horlahlekhon  any update needed here?

**Comment by horlahlekhon** [comment]
Yes, we should talk when you are chanced

**Comment by bolorundurovj** [comment]
@horlahlekhon `POST | https://carpadi.herokuapp.com/api/v1/admins/trades/disburse-rots/` returns the error below. 

Payload : `{"car":"66cd8fad-5152-41dd-b7d5-f2b51e137e7f"}`

Screenshot 2022-09-09 at 16 47 39

**Comment by horlahlekhon** [comment]
```bash
curl --location --request POST 'localhost:8000/api/v1/admins/trades/disburse-rots/?trade=35f35215-8622-4636-955e-add45ffb4db8' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjYyNjkyNjg1LCJqdGkiOiJkMTEzMDBhODY4OTc0NTU4YjhjYWRiZmFjZDIxMzIwOSIsInVzZXJfaWQiOiI4NTQxYzMzYy02ZWQyLTRjYWYtYWUwZi05MjQ3MzVkM2ZiZTUiLCJkZXZpY2VfaW1laSI6bnVsbH0.7vLKL3hPLzXnBmTrcsShw_F4oIrQ0WSXo2tvejRAQY8'

```

**Comment by horlahlekhon** [comment]
your query is not correct

**Comment by bolorundurovj** [comment]
I am getting this error now 
Screenshot 2022-09-09 at 19 08 48

**Comment by bolorundurovj** [comment]
Will refactor that

**Pull request merged**
